import {
  Incident,
  Agent,
  ApprovalRequest,
  ToolDefinition,
  SystemHealthSummary,
  ActivityEvent,
  RecoveryStats,
} from "@/types";

export const mockSystemHealth: SystemHealthSummary = {
  defconLevel: 2,
  defconLabel: "ELEVATED THREAT",
  clusterHealth: "DEGRADED",
  activeIncidentsCount: 3,
  pendingApprovalsCount: 2,
  activeAgentsCount: 5,
  mttd: "48s",
  mttm: "3m 42s",
  autonomousRemediationRate: 84.6,
  systemLatencyMs: 28,
  services: [
    { name: "api-gateway-mesh", status: "critical", latency: 242, errorRate: 14.8, node: "k8s-us-east-1a", trafficRps: 42100 },
    { name: "auth-engine-v2", status: "warning", latency: 68, errorRate: 3.2, node: "k8s-us-east-1b", trafficRps: 28900 },
    { name: "checkout-billing", status: "critical", latency: 185, errorRate: 8.6, node: "k8s-us-east-1c", trafficRps: 18400 },
    { name: "postgres-primary-prod", status: "warning", latency: 45, errorRate: 1.1, node: "rds-db-primary", trafficRps: 12200 },
    { name: "redis-sentinel-cache", status: "healthy", latency: 2.1, errorRate: 0.0, node: "redis-cluster-0", trafficRps: 84500 },
    { name: "kafka-telemetry-bus", status: "healthy", latency: 4.8, errorRate: 0.02, node: "kafka-broker-3", trafficRps: 94000 },
    { name: "inventory-worker-pool", status: "healthy", latency: 14, errorRate: 0.0, node: "k8s-us-east-1a", trafficRps: 8400 },
    { name: "search-vector-engine", status: "healthy", latency: 22, errorRate: 0.04, node: "k8s-us-east-1b", trafficRps: 15600 },
  ],
};

export const mockAgents: Agent[] = [
  {
    id: "agent-sre-01",
    name: "Sentinel-SRE",
    codename: "TITAN-ALPHA",
    role: "Autonomous Site Reliability & Outage Mitigator",
    status: "mitigating",
    autonomyLevel: "L3_AUTONOMOUS",
    model: "Gemini 1.5 Pro / SRE-Tuned",
    avatarSeed: "titan",
    currentTask: "Orchestrating Helm rollback on api-gateway-mesh v3.8.2",
    currentIncidentId: "INC-8921",
    stats: {
      incidentsResolved: 148,
      actionsExecuted: 624,
      approvalSuccessRate: 98.4,
      avgResolutionTime: "3m 12s",
      tokenUsageToday: 842100,
    },
    allowedTools: ["kubectl_exec", "argo_cd_sync", "datadog_trace_query", "slack_pagerduty_sync"],
    systemPromptSummary: "Execute real-time cluster triage, calculate blast radius, generate idempotent rollback plans, and resolve container crashes without downtime.",
  },
  {
    id: "agent-sec-02",
    name: "Aegis-SecOps",
    codename: "AEGIS-SHIELD",
    role: "L7 Threat Detection & Automated Countermeasures",
    status: "investigating",
    autonomyLevel: "L2_HUMAN_IN_THE_LOOP",
    model: "Claude 3.5 Sonnet / Sec-Defense",
    avatarSeed: "aegis",
    currentTask: "Analyzing botnet ASN distribution & generating WAF IP block list",
    currentIncidentId: "INC-8919",
    stats: {
      incidentsResolved: 89,
      actionsExecuted: 312,
      approvalSuccessRate: 99.1,
      avgResolutionTime: "2m 04s",
      tokenUsageToday: 620400,
    },
    allowedTools: ["aws_waf_rule_inject", "datadog_trace_query", "slack_pagerduty_sync"],
    systemPromptSummary: "Detect anomalous payload signatures, credential stuffing clusters, and coordinate edge rate-limiting rules.",
  },
  {
    id: "agent-k8s-03",
    name: "Chronos-K8s",
    codename: "CHRONOS-POD",
    role: "Kubernetes Fleet Health & HPA Controller",
    status: "active",
    autonomyLevel: "L3_AUTONOMOUS",
    model: "Gemini 1.5 Flash",
    avatarSeed: "chronos",
    currentTask: "Auto-tuning horizontal pod autoscaling threshold for order-service",
    stats: {
      incidentsResolved: 215,
      actionsExecuted: 1104,
      approvalSuccessRate: 99.7,
      avgResolutionTime: "1m 15s",
      tokenUsageToday: 412000,
    },
    allowedTools: ["kubectl_exec", "argo_cd_sync"],
    systemPromptSummary: "Monitor cgroup memory limits, CPU throttling spikes, and autonomously execute pod drains during node taint events.",
  },
  {
    id: "agent-db-04",
    name: "Nexus-DBA",
    codename: "NEXUS-SQL",
    role: "Database Reliability & Deadlock Resolver",
    status: "idle",
    autonomyLevel: "L2_HUMAN_IN_THE_LOOP",
    model: "Gemini 1.5 Pro",
    avatarSeed: "nexus",
    currentTask: "Standby for read replica sync verification",
    stats: {
      incidentsResolved: 56,
      actionsExecuted: 182,
      approvalSuccessRate: 97.2,
      avgResolutionTime: "5m 20s",
      tokenUsageToday: 295000,
    },
    allowedTools: ["postgres_drain_pool", "datadog_trace_query"],
    systemPromptSummary: "Identify slow table locks, pg_stat_activity connection spikes, and execute safe connection pooling adjustments.",
  },
  {
    id: "agent-forensics-05",
    name: "TraceHound",
    codename: "HOUND-EBPF",
    role: "eBPF Kernel Profiler & Trace Forensics",
    status: "active",
    autonomyLevel: "L1_ADVISORY",
    model: "GPT-4o Forensics",
    avatarSeed: "hound",
    currentTask: "Capturing kernel socket drop metrics on node k8s-us-east-1a",
    stats: {
      incidentsResolved: 41,
      actionsExecuted: 88,
      approvalSuccessRate: 100.0,
      avgResolutionTime: "4m 50s",
      tokenUsageToday: 350000,
    },
    allowedTools: ["datadog_trace_query"],
    systemPromptSummary: "Inspect kernel socket buffer overflows, TCP retransmits, and correlate distributed traces across Istio service mesh.",
  },
];

export const mockIncidents: Incident[] = [
  {
    id: "INC-8921",
    fingerprint: "a9f81e32-k8s-gateway-502",
    title: "API Gateway 502 Cascading Spike & Envoy Upstream Connection Drops",
    severity: "SEV-0",
    status: "mitigating",
    leadAgentId: "agent-sre-01",
    affectedServices: ["api-gateway-mesh", "checkout-billing", "auth-engine-v2"],
    blastRadius: "~42,000 req/sec (18% user transactions impacted)",
    summary: "Following deployment v3.8.2 of api-gateway-mesh, envoy connection pool exhausted due to unhandled gRPC keepalive timeout, triggering widespread HTTP 502s.",
    createdAt: "2026-09-28T07:38:12Z",
    updatedAt: "2026-09-28T07:44:50Z",
    duration: "14m 20s",
    rca: {
      rootCause: "Commit 9bf2ad introduced an aggressive 250ms upstream gRPC keepalive ping without configuring keepalive permit without calls. Upstream service mesh Envoy instances closed 8,400 active socket descriptors simultaneously.",
      confidence: 96.8,
      evidence: [
        {
          type: "commit",
          content: "git commit 9bf2ad4: 'perf: tune grpc keepalive time to 250ms for low latency'",
          timestamp: "2026-09-28T07:30:00Z",
        },
        {
          type: "metric",
          content: "envoy_cluster_upstream_cx_connect_timeout spiked +1,480% on us-east-1a",
          timestamp: "2026-09-28T07:38:05Z",
        },
        {
          type: "log",
          content: "[envoy.upstream] upstream connect error or disconnect/reset before headers. reset reason: connection termination",
          timestamp: "2026-09-28T07:38:12Z",
        },
      ],
      suggestedMitigation: "Execute instant Helm canary rollback to v3.8.1 and flush connection pools across 12 gateway ingress pods.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Divert 30% ingress traffic to secondary standby cluster (us-east-1b)",
        command: "kubectl patch virtualservice api-gateway -p '{\"spec\":{\"hosts\":[\"*\"]}}'",
        status: "completed",
        executedBy: "Sentinel-SRE",
        executedAt: "07:40:15 UTC",
      },
      {
        id: "step-2",
        title: "Emergency Helm Rollback from v3.8.2 to v3.8.1",
        command: "helm rollback api-gateway-mesh 14 --namespace production --wait",
        status: "requires_approval",
        executedBy: "Sentinel-SRE",
        executedAt: "07:42:00 UTC",
      },
      {
        id: "step-3",
        title: "Restart envoy sidecars on checkout-billing pod replica set",
        command: "kubectl rollout restart deployment/checkout-billing -n prod",
        status: "pending",
        executedBy: "Chronos-K8s",
      },
      {
        id: "step-4",
        title: "Verify p99 latency drop below 80ms baseline and error rate < 0.1%",
        status: "pending",
        executedBy: "Sentinel-SRE",
      },
    ],
    telemetry: [
      { timestamp: "07:30", errorRate: 0.05, latencyMs: 32, requestCount: 38400 },
      { timestamp: "07:32", errorRate: 0.06, latencyMs: 34, requestCount: 39100 },
      { timestamp: "07:34", errorRate: 0.04, latencyMs: 33, requestCount: 40200 },
      { timestamp: "07:36", errorRate: 0.12, latencyMs: 38, requestCount: 41200 },
      { timestamp: "07:38", errorRate: 14.8, latencyMs: 242, requestCount: 42100 },
      { timestamp: "07:40", errorRate: 18.2, latencyMs: 310, requestCount: 42500 },
      { timestamp: "07:42", errorRate: 11.4, latencyMs: 190, requestCount: 41800 },
      { timestamp: "07:44", errorRate: 7.2, latencyMs: 145, requestCount: 42000 },
    ],
    logs: [
      { id: "log-1", timestamp: "07:38:02", level: "WARN", source: "envoy-ingress-04", message: "upstream connection pool saturation warning (threshold 80% reached)" },
      { id: "log-2", timestamp: "07:38:12", level: "ERROR", source: "api-gateway-mesh", message: "502 Bad Gateway emitted for /v1/checkout/session (upstream reset)" },
      { id: "log-3", timestamp: "07:38:14", level: "FATAL", source: "sentinel-watcher", message: "CRITICAL: Error rate threshold exceeded (>5% over 1min window)" },
      { id: "log-4", timestamp: "07:38:18", level: "AGENT", source: "Sentinel-SRE", message: "Incident INC-8921 opened. Lead investigator assigned: TITAN-ALPHA. Initiating automated blast radius mapping." },
      { id: "log-5", timestamp: "07:39:45", level: "AGENT", source: "Sentinel-SRE", message: "RCA calculated (confidence 96.8%). Root cause isolated to commit 9bf2ad4 in api-gateway-mesh v3.8.2." },
      { id: "log-6", timestamp: "07:40:15", level: "AGENT", source: "Sentinel-SRE", message: "Mitigation Step 1 executed: Diverted 30% traffic to cluster us-east-1b." },
      { id: "log-7", timestamp: "07:42:00", level: "AGENT", source: "Sentinel-SRE", message: "Approval request APP-401 submitted for Helm Rollback. Awaiting Human-In-The-Loop confirmation." },
    ],
  },
  {
    id: "INC-8919",
    fingerprint: "c3d4a1b0-ddos-auth-credential",
    title: "Distributed Credential Stuffing & Layer-7 HTTP Flood on /api/v2/auth/login",
    severity: "SEV-1",
    status: "approval_required",
    leadAgentId: "agent-sec-02",
    affectedServices: ["auth-engine-v2", "api-gateway-mesh"],
    blastRadius: "12,400 rogue IPs targeting authentication endpoints",
    summary: "High-volume credential stuffing campaign detected originating from ASN 14061 (Tor/residential proxy exit nodes), generating 2,400 failed login attempts/sec.",
    createdAt: "2026-09-28T07:22:40Z",
    updatedAt: "2026-09-28T07:41:10Z",
    duration: "22m 10s",
    rca: {
      rootCause: "Coordinated botnet brute-force attack exploiting lack of IP reputation score thresholding on v2 auth login routes.",
      confidence: 94.2,
      evidence: [
        {
          type: "metric",
          content: "Auth failure rate rose from 1.8% to 64.2% within 180 seconds",
          timestamp: "2026-09-28T07:23:00Z",
        },
        {
          type: "log",
          content: "Repeated invalid bcrypt hash comparisons from IP block 185.220.101.0/24 with synthetic User-Agent headers",
          timestamp: "2026-09-28T07:24:12Z",
        },
      ],
      suggestedMitigation: "Deploy dynamic AWS WAF rate-limiting rule (max 20 req/5m per IP) and block ASN 14061 edge CIDRs.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Enable Cloudflare Under-Attack Mode for /api/v2/auth/*",
        status: "completed",
        executedBy: "Aegis-SecOps",
        executedAt: "07:26:00 UTC",
      },
      {
        id: "step-2",
        title: "Inject WAF Rate-Limiting Rule & Ban CIDR 185.220.101.0/24",
        command: "aws wafv2 update-ip-set --name Blocked-Botnet-ASN14061 --addresses 185.220.101.0/24",
        status: "requires_approval",
        executedBy: "Aegis-SecOps",
        executedAt: "07:31:00 UTC",
      },
      {
        id: "step-3",
        title: "Invalidate leaked session tokens generated within attack window",
        status: "pending",
        executedBy: "Aegis-SecOps",
      },
    ],
    telemetry: [
      { timestamp: "07:20", errorRate: 1.2, latencyMs: 22, requestCount: 5200 },
      { timestamp: "07:22", errorRate: 14.5, latencyMs: 45, requestCount: 14200 },
      { timestamp: "07:24", errorRate: 48.0, latencyMs: 98, requestCount: 28900 },
      { timestamp: "07:26", errorRate: 52.4, latencyMs: 112, requestCount: 29500 },
      { timestamp: "07:28", errorRate: 41.0, latencyMs: 84, requestCount: 26000 },
      { timestamp: "07:30", errorRate: 32.8, latencyMs: 68, requestCount: 21000 },
    ],
    logs: [
      { id: "sec-1", timestamp: "07:22:40", level: "WARN", source: "auth-engine", message: "Spike in HTTP 401 Unauthorized responses on /login" },
      { id: "sec-2", timestamp: "07:24:00", level: "FATAL", source: "aegis-scanner", message: "THREAT ALERT: Credential stuffing pattern identified (ASN 14061)" },
      { id: "sec-3", timestamp: "07:26:00", level: "AGENT", source: "Aegis-SecOps", message: "Activated edge challenge verification for untrusted autonomous systems." },
      { id: "sec-4", timestamp: "07:31:00", level: "AGENT", source: "Aegis-SecOps", message: "Created Approval Request APP-402 for WAF IP Set deployment." },
    ],
  },
  {
    id: "INC-8914",
    fingerprint: "f0e9d8c7-postgres-replica-lag",
    title: "PostgreSQL Read Replica Lag Exceeding 180s & Connection Starvation",
    severity: "SEV-2",
    status: "investigating",
    leadAgentId: "agent-db-04",
    affectedServices: ["postgres-primary-prod", "inventory-worker-pool"],
    blastRadius: "Read traffic fallback to primary database; latency degradation",
    summary: "Unindexed analytical query triggered sequential table scan on 42M row table, blocking WAL replication thread.",
    createdAt: "2026-09-28T06:55:10Z",
    updatedAt: "2026-09-28T07:35:00Z",
    duration: "49m 40s",
    rca: {
      rootCause: "Long-running query `SELECT * FROM audit_events WHERE created_at > ...` holding shared buffer lock on replica-02.",
      confidence: 91.5,
      evidence: [
        {
          type: "metric",
          content: "pg_stat_replication.write_lag exceeded 184 seconds on rds-read-02",
          timestamp: "2026-09-28T07:05:00Z",
        },
      ],
      suggestedMitigation: "Terminate blocking backend PID 41802 and divert read queries to replica-01.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Kill blocking query PID 41802 via pg_terminate_backend()",
        command: "SELECT pg_terminate_backend(41802);",
        status: "completed",
        executedBy: "Nexus-DBA",
        executedAt: "07:12:00 UTC",
      },
      {
        id: "step-2",
        title: "Verify WAL replication lag returns under 500ms",
        status: "running",
        executedBy: "Nexus-DBA",
      },
    ],
    telemetry: [
      { timestamp: "06:50", errorRate: 0.0, latencyMs: 12, requestCount: 18000 },
      { timestamp: "07:00", errorRate: 0.2, latencyMs: 38, requestCount: 19500 },
      { timestamp: "07:10", errorRate: 1.1, latencyMs: 82, requestCount: 20400 },
      { timestamp: "07:20", errorRate: 0.4, latencyMs: 45, requestCount: 20100 },
    ],
    logs: [
      { id: "db-1", timestamp: "06:55:10", level: "WARN", source: "postgres-exporter", message: "WAL sender lagging behind by 124MB" },
      { id: "db-2", timestamp: "07:12:00", level: "AGENT", source: "Nexus-DBA", message: "Terminated query PID 41802. Replication catch-up initiated." },
    ],
  },
  {
    id: "INC-8902",
    fingerprint: "b2c3d4e5-worker-oom-crash",
    title: "Memory Leak Detected in payment-worker-v3 (OOMKilled Cycle)",
    severity: "SEV-3",
    status: "resolved",
    leadAgentId: "agent-k8s-03",
    affectedServices: ["checkout-billing"],
    blastRadius: "Isolated to background payment receipt generator worker",
    summary: "Unclosed PDF rendering file descriptors caused gradual memory consumption until cgroup limit hit (512MB).",
    createdAt: "2026-09-28T04:10:00Z",
    updatedAt: "2026-09-28T04:22:15Z",
    duration: "12m 15s",
    rca: {
      rootCause: "Ghostscript subprocess handles not freed after invoice rendering.",
      confidence: 99.0,
      evidence: [
        {
          type: "metric",
          content: "container_memory_working_set_bytes hit 512Mi limit",
          timestamp: "2026-09-28T04:15:00Z",
        },
      ],
      suggestedMitigation: "Bump temporary cgroup limit to 1024MB and trigger auto-restart after 200 jobs.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Adjust memory limits in pod spec",
        command: "kubectl set resources deployment payment-worker --limits=memory=1Gi",
        status: "completed",
        executedBy: "Chronos-K8s",
        executedAt: "04:18:00 UTC",
      },
      {
        id: "step-2",
        title: "Validate zero restarts over 15 minute interval",
        status: "completed",
        executedBy: "Chronos-K8s",
        executedAt: "04:22:00 UTC",
      },
    ],
    telemetry: [
      { timestamp: "04:00", errorRate: 0.0, latencyMs: 18, requestCount: 8400 },
      { timestamp: "04:10", errorRate: 2.4, latencyMs: 24, requestCount: 8900 },
      { timestamp: "04:20", errorRate: 0.0, latencyMs: 19, requestCount: 8800 },
    ],
    logs: [
      { id: "oom-1", timestamp: "04:15:02", level: "FATAL", source: "kernel", message: "Task payment-worker (pid 9122) killed due to cgroup out of memory" },
      { id: "oom-2", timestamp: "04:18:00", level: "AGENT", source: "Chronos-K8s", message: "Patched deployment memory ceiling. Restart loop halted." },
      { id: "oom-3", timestamp: "04:22:15", level: "AGENT", source: "Chronos-K8s", message: "Incident resolved. Post-mortem ticket generated: JIRA-SRE-882." },
    ],
  },
];

export const mockApprovals: ApprovalRequest[] = [
  {
    id: "APP-401",
    incidentId: "INC-8921",
    incidentTitle: "API Gateway 502 Cascading Spike & Envoy Upstream Drops",
    incidentSeverity: "SEV-0",
    agentId: "agent-sre-01",
    agentName: "Sentinel-SRE (TITAN-ALPHA)",
    title: "Emergency Helm Canary Rollback: api-gateway-mesh v3.8.2 -> v3.8.1",
    action: "Emergency Helm Canary Rollback",
    target: "api-gateway-mesh (12 Ingress Pods, us-east-1a)",
    reason: "Ingress Envoy keepalive timeout set to 250ms causing cascading 502 socket resets and 14.8% error rate across 42,000 req/s.",
    expectedResult: "Restores gRPC keepalive baseline to 30s; drops HTTP 502 error rate below 0.05% in under 90s with zero downtime via rolling update.",
    description: "Sentinel-SRE requests immediate automated rollback of ingress gateway chart to previous stable release to eliminate gRPC keepalive timeouts.",
    riskLevel: "CRITICAL",
    status: "pending",
    createdAt: "2026-09-28T07:42:00Z",
    expiresInSeconds: 340,
    blastRadius: [
      "12 Envoy Ingress Pods",
      "Production Ingress Route Traffic (42,000 req/sec)",
      "Zero-downtime rolling replacement guarantee",
    ],
    toolName: "argo_cd_sync",
    actionDiff: {
      type: "cli",
      before: "# Current Deployment: api-gateway-mesh v3.8.2\ngrpc:\n  keepalive:\n    time: 250ms # <-- BUG: Causes upstream socket termination\n    timeout: 100ms",
      after: "# Proposed Rollback: api-gateway-mesh v3.8.1\ngrpc:\n  keepalive:\n    time: 30000ms # Restored to 30s stable baseline\n    timeout: 5000ms\n\n$ helm rollback api-gateway-mesh 14 --namespace production --wait",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Target Revision Integrity & Signature",
        status: "passed",
        details: "Revision 14 hash sha256:4a81bc verified against GitOps main repository.",
      },
      {
        id: "sc-2",
        name: "Standby Capacity Verification",
        status: "passed",
        details: "Secondary cluster us-east-1b healthy with 140% headroom.",
      },
      {
        id: "sc-3",
        name: "Database Migration Incompatibility",
        status: "passed",
        details: "No schema migrations occurred between v3.8.1 and v3.8.2.",
      },
      {
        id: "sc-4",
        name: "Active WebSocket Connections Drop",
        status: "warning",
        details: "Estimated 1,200 persistent WebSocket sessions will be cleanly drained.",
      },
    ],
  },
  {
    id: "APP-402",
    incidentId: "INC-8919",
    incidentTitle: "Distributed Credential Stuffing on /api/v2/auth/login",
    incidentSeverity: "SEV-1",
    agentId: "agent-sec-02",
    agentName: "Aegis-SecOps (AEGIS-DEFENSE)",
    title: "WAF Rate-Limiting Rule Injection: Block ASN 14061 & Subnet 185.220.101.0/24",
    action: "Dynamic AWS WAF Rate-Limiting & CIDR Block Injection",
    target: "Edge AWS WAF ACL (prod-global-waf-01, ASN 14061)",
    reason: "High-volume distributed credential stuffing botnet generating 2,400 failed login attempts/sec on /api/v2/auth/login from residential proxy exit nodes.",
    expectedResult: "Drops rogue brute-force attacks by 99.4% while preserving 100% of verified corporate and customer sessions.",
    description: "Aegis-SecOps requests authorization to inject IP block rule into AWS WAF ACL to halt high-speed botnet credential stuffing.",
    riskLevel: "HIGH",
    status: "pending",
    createdAt: "2026-09-28T07:31:00Z",
    expiresInSeconds: 580,
    blastRadius: [
      "Edge AWS WAF ACL: prod-global-waf-01",
      "Affected IP range: 185.220.101.0/24 (Tor exit cluster)",
      "Zero legitimate corporate VPN overlaps verified",
    ],
    toolName: "aws_waf_rule_inject",
    actionDiff: {
      type: "cli",
      before: "# AWS WAF IP Set: Blocked-Tor-Exits\nExisting rules: 412 entries\nAction: BLOCK",
      after: "# Adding entries:\n+ 185.220.101.0/24 (Tagged: Botnet-Credential-Stuffing)\n+ Rate-Limit: 20 req/5min for ASN 14061\n\n$ aws wafv2 update-ip-set --name Blocked-Botnet-ASN14061 ...",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "False Positive IP Whitelist Collision",
        status: "passed",
        details: "Checked against corporate NAT IPs, payment gateways, and uptime checkers.",
      },
      {
        id: "sc-2",
        name: "Rule Priority Limit Check",
        status: "passed",
        details: "WCU cost is 25 units. Current WCU: 850/1500.",
      },
    ],
  },
  {
    id: "APP-403",
    incidentId: "INC-8921",
    incidentTitle: "API Gateway 502 Cascading Spike & Envoy Upstream Drops",
    incidentSeverity: "SEV-0",
    agentId: "agent-k8s-03",
    agentName: "Chronos-K8s (CHRONOS-AUTOSCALE)",
    title: "Kubernetes HPA Maximum Scale Elevation: checkout-billing (8 -> 24 replicas)",
    action: "HPA Replica Upper-Bound Scale Elevation",
    target: "checkout-billing deployment (prod-us-east-1a)",
    reason: "Downstream checkout queue processing latency increased to 185ms due to upstream retry bursts from the gateway event.",
    expectedResult: "Triples worker throughput, drains queued transactions within 120 seconds, and normalizes p99 latency to 28ms baseline.",
    description: "Chronos-K8s requests temporary autoscaling ceiling expansion to absorb retry backpressure from upstream gateway recovery.",
    riskLevel: "MEDIUM",
    status: "pending",
    createdAt: "2026-09-28T07:35:12Z",
    expiresInSeconds: 720,
    blastRadius: [
      "checkout-billing deployment (Kubernetes Pod replicas: 8 -> 24)",
      "Node pool compute allocation (+4.2 vCPU, +8.4GB RAM)",
      "Zero disruption to live user transactions",
    ],
    toolName: "kubectl_exec",
    actionDiff: {
      type: "cli",
      before: "apiVersion: autoscaling/v2\nspec:\n  maxReplicas: 8\n  minReplicas: 4",
      after: "apiVersion: autoscaling/v2\nspec:\n  maxReplicas: 24\n  minReplicas: 8\n\n$ kubectl scale deployment/checkout-billing --replicas=16 -n prod",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Cluster Node Pool CPU/Memory Quota",
        status: "passed",
        details: "Node pool has 36 available vCPUs and 64GB unreserved memory.",
      },
      {
        id: "sc-2",
        name: "Database Connection Pool Limit",
        status: "passed",
        details: "Max connections per pod set to 5. Total db connections well under RDS max.",
      },
    ],
  },
  {
    id: "APP-404",
    incidentId: "INC-8914",
    incidentTitle: "PostgreSQL Read Replica Lag Exceeding 180s",
    incidentSeverity: "SEV-2",
    agentId: "agent-db-04",
    agentName: "Nexus-DBA (NEXUS-RECOVERY)",
    title: "Redis Session Cache Connection Pool Rebalance: shard-02 -> shard-04",
    action: "Redis Cache Socket Pool Rebalance",
    target: "redis-session-cluster (Nodes: shard-02, shard-03, shard-04)",
    reason: "Re-distribute idle socket handles to prevent memory fragmentation on hotspot nodes during traffic diversion.",
    expectedResult: "Smooths socket load evenly across cluster with 0 evicted keys and 0 customer session disruptions.",
    description: "Nexus-DBA requests automated redistribution of Redis client connection pools to balance node load.",
    riskLevel: "LOW",
    status: "pending",
    createdAt: "2026-09-28T07:37:45Z",
    expiresInSeconds: 1200,
    blastRadius: [
      "redis-session-cluster (3 read cache shards)",
      "Internal non-persistent cache only (0 persistent data impact)",
    ],
    toolName: "redis_cluster_ctl",
    actionDiff: {
      type: "cli",
      before: "# Redis maxclients on shard-02: 10000 (Current connections: 8900)",
      after: "$ redis-cli -c -h redis-cluster-01 CLUSTER REBALANCE --pipeline 10 --timeout 5000",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Key Eviction & TTL Integrity",
        status: "passed",
        details: "Active key replication verified with 0ms memory eviction lag.",
      },
    ],
  },
  {
    id: "APP-398",
    incidentId: "INC-8914",
    incidentTitle: "PostgreSQL Read Replica Lag Exceeding 180s",
    incidentSeverity: "SEV-2",
    agentId: "agent-db-04",
    agentName: "Nexus-DBA",
    title: "PostgreSQL Max Connection Pool Dynamic Scale-Up (300 -> 600)",
    action: "PostgreSQL Connection Pool Dynamic Scale-Up",
    target: "RDS PostgreSQL Primary (rds-db-primary)",
    reason: "Dynamic RDS parameter group modification to prevent connection starvation while replica catches up.",
    expectedResult: "Doubled concurrent query capacity with safe memory allocation (<2.4GB).",
    description: "Dynamic RDS parameter group modification to prevent connection starvation while replica catches up.",
    riskLevel: "MEDIUM",
    status: "approved",
    createdAt: "2026-09-28T07:10:00Z",
    expiresInSeconds: 0,
    blastRadius: ["RDS Postgres Primary: rds-db-primary"],
    toolName: "postgres_drain_pool",
    actionDiff: {
      type: "sql",
      before: "max_connections = 300;",
      after: "ALTER SYSTEM SET max_connections = 600;\nSELECT pg_reload_conf();",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Memory Consumption Safety Margin",
        status: "passed",
        details: "600 connections * 4MB work_mem = 2.4GB. Instance has 32GB free RAM.",
      },
    ],
    decidedAt: "2026-09-28T07:11:30Z",
    decidedBy: "Lead SRE (Samay)",
  },
  {
    id: "APP-395",
    incidentId: "INC-8902",
    incidentTitle: "Anomalous Outbound DNS Exfiltration Probe",
    incidentSeverity: "SEV-1",
    agentId: "agent-sec-02",
    agentName: "Aegis-SecOps",
    title: "Total Border Gateway Protocol (BGP) Null-Route for ASN 4134",
    action: "BGP Null-Route Edge Transit Cutoff",
    target: "Autonomous System Border Router (ASBR-01)",
    reason: "Suspected external UDP reflection attack on legacy port 53 causing transit packet drops.",
    expectedResult: "Null-routes upstream ISP peer but would drop secondary transit links.",
    description: "Proposed complete cutoff of ASBR transit peer link to isolate rogue reflection traffic.",
    riskLevel: "HIGH",
    status: "rejected",
    createdAt: "2026-09-28T06:45:00Z",
    expiresInSeconds: 0,
    blastRadius: ["Global Transit Link ASBR-01", "Secondary Asia-Pacific route"],
    toolName: "bgp_router_exec",
    actionDiff: {
      type: "cli",
      before: "bgp route 185.0.0.0/8 via 192.168.1.1",
      after: "ip route 185.0.0.0/8 Null0",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Secondary Transit Redundancy",
        status: "failed",
        details: "Alternative ISP peering route not yet fully converged.",
      },
    ],
    decidedAt: "2026-09-28T06:47:15Z",
    decidedBy: "Incident Commander (Samay)",
  },
];

export const mockTools: ToolDefinition[] = [
  {
    id: "kubectl_exec",
    name: "Kubernetes Cluster Controller (kubectl)",
    category: "kubernetes",
    safetyTier: "destructive",
    description: "Execute rollouts, pod drains, resource patching, and pod restarts across production EKS clusters.",
    requiredApprovalRole: "SRE_Lead",
    enabled: true,
    rateLimit: "60 req/min",
    allowedAgents: ["agent-sre-01", "agent-k8s-03"],
    totalExecutions: 4812,
    lastExecutedAt: "2026-09-28T07:40:15Z",
    recentExecutions: [
      {
        id: "ex-1",
        agentId: "agent-sre-01",
        incidentId: "INC-8921",
        command: "kubectl patch virtualservice api-gateway -p '{\"spec\":{\"hosts\":[\"*\"]}}'",
        durationMs: 412,
        exitCode: 0,
        timestamp: "07:40:15",
      },
      {
        id: "ex-2",
        agentId: "agent-k8s-03",
        incidentId: "INC-8902",
        command: "kubectl set resources deployment payment-worker --limits=memory=1Gi",
        durationMs: 310,
        exitCode: 0,
        timestamp: "04:18:00",
      },
    ],
  },
  {
    id: "aws_waf_rule_inject",
    name: "AWS WAF & Shield Dynamic Filter",
    category: "network",
    safetyTier: "high_risk",
    description: "Inject real-time IP blocks, ASN rate limits, and captcha challenges on CloudFront & ALB edge nodes.",
    requiredApprovalRole: "SecOps_Lead",
    enabled: true,
    rateLimit: "20 req/min",
    allowedAgents: ["agent-sec-02"],
    totalExecutions: 894,
    lastExecutedAt: "2026-09-28T07:26:00Z",
    recentExecutions: [
      {
        id: "ex-3",
        agentId: "agent-sec-02",
        incidentId: "INC-8919",
        command: "aws wafv2 update-web-acl --name prod-alb-waf --default-action Challenge",
        durationMs: 780,
        exitCode: 0,
        timestamp: "07:26:00",
      },
    ],
  },
  {
    id: "postgres_drain_pool",
    name: "RDS PostgreSQL Session Terminator & Pool Tuner",
    category: "database",
    safetyTier: "destructive",
    description: "Terminate blocking query PIDs, adjust connection pool sizes, and manage read replica failovers.",
    requiredApprovalRole: "SRE_Lead",
    enabled: true,
    rateLimit: "30 req/min",
    allowedAgents: ["agent-db-04"],
    totalExecutions: 341,
    lastExecutedAt: "2026-09-28T07:12:00Z",
    recentExecutions: [
      {
        id: "ex-4",
        agentId: "agent-db-04",
        incidentId: "INC-8914",
        command: "SELECT pg_terminate_backend(41802);",
        durationMs: 84,
        exitCode: 0,
        timestamp: "07:12:00",
      },
    ],
  },
  {
    id: "argo_cd_sync",
    name: "ArgoCD GitOps Synchronizer",
    category: "kubernetes",
    safetyTier: "reversible",
    description: "Trigger GitOps git revision deployments, rollbacks, and sync wave verifications.",
    requiredApprovalRole: "Incident_Commander",
    enabled: true,
    rateLimit: "15 req/min",
    allowedAgents: ["agent-sre-01", "agent-k8s-03"],
    totalExecutions: 1940,
    lastExecutedAt: "2026-09-28T06:30:00Z",
    recentExecutions: [],
  },
  {
    id: "datadog_trace_query",
    name: "Telemetry APM & eBPF Distributed Trace Query",
    category: "cloud",
    safetyTier: "read_only",
    description: "Read-only introspection into p99 latency spikes, service maps, error traces, and kernel metrics.",
    requiredApprovalRole: "None",
    enabled: true,
    rateLimit: "300 req/min",
    allowedAgents: ["agent-sre-01", "agent-sec-02", "agent-db-04", "agent-forensics-05"],
    totalExecutions: 24900,
    lastExecutedAt: "2026-09-28T07:44:30Z",
    recentExecutions: [
      {
        id: "ex-5",
        agentId: "agent-forensics-05",
        command: "datadog query trace --service api-gateway-mesh --filter 'http.status_code:502' --limit 50",
        durationMs: 190,
        exitCode: 0,
        timestamp: "07:44:30",
      },
    ],
  },
  {
    id: "slack_pagerduty_sync",
    name: "PagerDuty Incident War-Room & Escalation Broadcaster",
    category: "communication",
    safetyTier: "read_only",
    description: "Post automated RCA summaries, blast radius charts, and escalate on-call engineering leads.",
    requiredApprovalRole: "None",
    enabled: true,
    rateLimit: "100 req/min",
    allowedAgents: ["agent-sre-01", "agent-sec-02"],
    totalExecutions: 1250,
    lastExecutedAt: "2026-09-28T07:38:18Z",
    recentExecutions: [],
  },
];

export const mockRecoveryStats: RecoveryStats = {
  mttd: "48s",
  mttm: "3m 42s",
  autonomousResolutionRate: 84.6,
  totalIncidentsResolved: 412,
  preventedDowntimeMinutes: 184,
  estimatedCostSaved: "$1,420,000",
  activeCanaryVerifications: 3,
  rollbackReliability: 99.2,
};

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: "act-1",
    timestamp: "07:44:30",
    category: "telemetry",
    agentName: "TraceHound",
    agentRole: "eBPF Kernel Profiler",
    summary: "eBPF socket drops normalized across us-east-1a after traffic diversion",
    details: "TCP drop rate dropped from 420/s to 3/s on ingress gateway interfaces",
    status: "success",
    targetResource: "k8s-us-east-1a",
  },
  {
    id: "act-2",
    timestamp: "07:42:00",
    category: "approval",
    agentName: "Sentinel-SRE",
    agentRole: "Site Reliability Mitigator",
    summary: "Approval request APP-401 submitted: Helm Rollback to v3.8.1",
    details: "Requires SRE Commander cryptographic confirmation",
    status: "pending",
    targetResource: "api-gateway-mesh",
  },
  {
    id: "act-3",
    timestamp: "07:40:15",
    category: "mitigation",
    agentName: "Sentinel-SRE",
    agentRole: "Site Reliability Mitigator",
    summary: "Diverted 30% ingress HTTP traffic to secondary cluster us-east-1b",
    details: "Patched Istio VirtualService weights in 380ms",
    status: "success",
    targetResource: "virtualservice/api-gateway",
  },
  {
    id: "act-4",
    timestamp: "07:38:18",
    category: "recovery",
    agentName: "SentinelOps Engine",
    agentRole: "Core Supervisor",
    summary: "SEV-0 Incident INC-8921 opened; lead assigned to TITAN-ALPHA",
    details: "Calculated blast radius ~42,000 req/sec across 3 downstream dependencies",
    status: "warning",
    targetResource: "INC-8921",
  },
  {
    id: "act-5",
    timestamp: "07:31:00",
    category: "security",
    agentName: "Aegis-SecOps",
    agentRole: "L7 Threat Detection",
    summary: "WAF IP block rule generated for botnet subnet 185.220.101.0/24",
    details: "Rate limiting injected: 20 req/5m per rogue ASN 14061 fingerprint",
    status: "pending",
    targetResource: "aws-waf-acl/prod",
  },
  {
    id: "act-6",
    timestamp: "07:26:00",
    category: "security",
    agentName: "Aegis-SecOps",
    agentRole: "L7 Threat Detection",
    summary: "Activated Cloudflare Under-Attack interstitial challenge for /api/v2/auth",
    details: "Halted 2,400 synthetic credential stuffing attempts per second",
    status: "success",
    targetResource: "cloudflare-edge",
  },
  {
    id: "act-7",
    timestamp: "07:12:00",
    category: "recovery",
    agentName: "Nexus-DBA",
    agentRole: "Database Reliability",
    summary: "Terminated blocking query PID 41802 holding buffer lock on rds-read-02",
    details: "WAL replication lag caught up from 184s to 240ms",
    status: "success",
    targetResource: "rds-db-primary",
  },
  {
    id: "act-8",
    timestamp: "04:22:15",
    category: "recovery",
    agentName: "Chronos-K8s",
    agentRole: "Fleet Health Controller",
    summary: "Resolved INC-8902: payment-worker memory limit patched to 1Gi",
    details: "Container OOMKilled loop halted. Post-mortem ticket JIRA-SRE-882 logged.",
    status: "success",
    targetResource: "payment-worker-v3",
  },
];

