import {
  Incident,
  Agent,
  ApprovalRequest,
  ToolDefinition,
  SystemHealthSummary,
  ActivityEvent,
  RecoveryStats,
} from "@/types";

export const mockSystemHealth: SystemHealthSummary = {
  defconLevel: 2,
  defconLabel: "ELEVATED THREAT",
  clusterHealth: "DEGRADED",
  activeIncidentsCount: 1,
  pendingApprovalsCount: 1,
  activeAgentsCount: 3,
  mttd: "42s",
  mttm: "4m 12s",
  autonomousRemediationRate: 92.4,
  systemLatencyMs: 24,
  services: [
    { name: "api-gateway", status: "critical", latency: 242, errorRate: 14.8, node: "gateway-node-01", trafficRps: 1850 },
    { name: "auth-service", status: "warning", latency: 64, errorRate: 3.1, node: "app-node-02", trafficRps: 920 },
    { name: "billing-service", status: "healthy", latency: 28, errorRate: 0.0, node: "app-node-03", trafficRps: 410 },
    { name: "postgres-primary", status: "healthy", latency: 8, errorRate: 0.0, node: "db-node-primary", trafficRps: 1200 },
  ],
};

export const mockAgents: Agent[] = [
  {
    id: "agent-diagnostic",
    name: "Diagnostic Agent",
    codename: "SENTINEL-DIAG",
    role: "Root Cause Analysis & Telemetry Correlation",
    status: "mitigating",
    autonomyLevel: "L3_AUTONOMOUS",
    model: "Gemini 2.0 Flash / RCA-Tuned",
    avatarSeed: "diag",
    currentTask: "Correlating commit 9bf2ad4 with upstream gRPC keepalive resets",
    currentIncidentId: "INC-8921",
    stats: {
      incidentsResolved: 48,
      actionsExecuted: 142,
      approvalSuccessRate: 99.2,
      avgResolutionTime: "2m 18s",
      tokenUsageToday: 38400,
    },
    allowedTools: ["check_health", "get_logs", "container_status"],
    systemPromptSummary: "Analyze container logs, inspect metric anomalies, correlate git commits, and isolate root causes with cryptographic certainty.",
  },
  {
    id: "agent-remediation",
    name: "Remediation Agent",
    codename: "SENTINEL-REMED",
    role: "Autonomous Mitigation & GitOps Execution",
    status: "mitigating",
    autonomyLevel: "L2_HUMAN_IN_THE_LOOP",
    model: "Gemini 2.0 Flash / SRE-Tuned",
    avatarSeed: "remed",
    currentTask: "Staged Helm canary rollback to v3.8.1 awaiting Commander approval",
    currentIncidentId: "INC-8921",
    stats: {
      incidentsResolved: 42,
      actionsExecuted: 118,
      approvalSuccessRate: 97.8,
      avgResolutionTime: "1m 45s",
      tokenUsageToday: 42100,
    },
    allowedTools: ["restart_container", "modify_config", "delete_container"],
    systemPromptSummary: "Plan minimal blast-radius mitigations, enforce safety guardrails, request human approval for high-risk operations, and apply safe rollbacks.",
  },
  {
    id: "agent-verification",
    name: "Verification Agent",
    codename: "SENTINEL-VERIFY",
    role: "Synthetic Probing & SLO Health Validation",
    status: "active",
    autonomyLevel: "L3_AUTONOMOUS",
    model: "Gemini 2.0 Flash / QA-Tuned",
    avatarSeed: "verify",
    currentTask: "Executing synthetic probe traffic across api-gateway ingress endpoints",
    currentIncidentId: "INC-8921",
    stats: {
      incidentsResolved: 46,
      actionsExecuted: 230,
      approvalSuccessRate: 100.0,
      avgResolutionTime: "45s",
      tokenUsageToday: 29800,
    },
    allowedTools: ["check_health", "get_logs"],
    systemPromptSummary: "Execute synthetic HTTP/gRPC test transactions, verify p99 latency SLAs, measure error rate recovery, and confirm zero regression before closing incidents.",
  },
];

export const mockIncidents: Incident[] = [
  {
    id: "INC-8921",
    fingerprint: "a9f81e32-k8s-gateway-502",
    title: "API Gateway 502 Cascading Spike & Upstream Connection Reset",
    severity: "SEV-0",
    status: "mitigating",
    leadAgentId: "agent-diagnostic",
    affectedServices: ["api-gateway", "auth-service"],
    blastRadius: "1,850 req/sec (14.8% user transactions experiencing 502)",
    summary: "Following deployment v3.8.2, api-gateway connection pool exhausted due to aggressive 250ms gRPC keepalive timeout, triggering widespread HTTP 502 errors.",
    createdAt: "2026-09-28T07:38:12Z",
    updatedAt: "2026-09-28T07:44:50Z",
    duration: "6m 38s",
    rca: {
      rootCause: "Commit 9bf2ad4 introduced an aggressive 250ms upstream gRPC keepalive ping without keepalive permit without calls. Upstream gateway instances closed active socket descriptors simultaneously.",
      confidence: 97.4,
      evidence: [
        {
          type: "commit",
          content: "git commit 9bf2ad4: 'perf: tune grpc keepalive time to 250ms for low latency'",
          timestamp: "2026-09-28T07:30:00Z",
        },
        {
          type: "metric",
          content: "upstream_cx_connect_timeout spiked +1,480% on gateway-node-01",
          timestamp: "2026-09-28T07:38:05Z",
        },
        {
          type: "log",
          content: "[envoy.upstream] upstream connect error or disconnect/reset before headers. reset reason: connection termination",
          timestamp: "2026-09-28T07:38:12Z",
        },
      ],
      suggestedMitigation: "Execute Helm canary rollback to v3.8.1 to restore stable 30s keepalive baseline.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Diagnostic Agent: Root cause triage & socket reset isolation",
        status: "completed",
        executedBy: "Diagnostic Agent",
        executedAt: "07:38:40 UTC",
      },
      {
        id: "step-2",
        title: "First Remediation: Restart gateway pods (restart_container)",
        command: "docker restart api-gateway-01 api-gateway-02",
        status: "completed",
        executedBy: "Remediation Agent",
        executedAt: "07:39:30 UTC",
      },
      {
        id: "step-3",
        title: "Verification Failed: 12.4% error rate persists after restart",
        status: "failed",
        executedBy: "Verification Agent",
        executedAt: "07:40:15 UTC",
      },
      {
        id: "step-4",
        title: "Re-Diagnosis: Isolated commit 9bf2ad4 keepalive regression",
        status: "completed",
        executedBy: "Diagnostic Agent",
        executedAt: "07:41:00 UTC",
      },
      {
        id: "step-5",
        title: "Second Remediation: Helm Canary Rollback to v3.8.1 (APP-401)",
        command: "helm rollback api-gateway 14 --namespace production --wait",
        status: "requires_approval",
        executedBy: "Remediation Agent",
        executedAt: "07:42:00 UTC",
      },
      {
        id: "step-6",
        title: "Verification Suite: Latency & error rate SLA validation",
        status: "pending",
        executedBy: "Verification Agent",
      },
    ],
    telemetry: [
      { timestamp: "07:30", errorRate: 0.04, latencyMs: 24, requestCount: 1800 },
      { timestamp: "07:34", errorRate: 0.05, latencyMs: 25, requestCount: 1820 },
      { timestamp: "07:38", errorRate: 14.8, latencyMs: 242, requestCount: 1850 },
      { timestamp: "07:40", errorRate: 12.4, latencyMs: 210, requestCount: 1840 },
      { timestamp: "07:42", errorRate: 9.8, latencyMs: 165, requestCount: 1810 },
      { timestamp: "07:44", errorRate: 6.2, latencyMs: 110, requestCount: 1830 },
    ],
    logs: [
      { id: "log-1", timestamp: "07:38:02", level: "WARN", source: "api-gateway", message: "upstream connection pool saturation warning (threshold 80% reached)" },
      { id: "log-2", timestamp: "07:38:12", level: "FATAL", source: "api-gateway", message: "502 Bad Gateway: upstream reset before headers" },
      { id: "log-3", timestamp: "07:38:40", level: "AGENT", source: "Diagnostic Agent", message: "INC-8921 opened. Initial triage indicates upstream connection drops." },
      { id: "log-4", timestamp: "07:39:30", level: "AGENT", source: "Remediation Agent", message: "First mitigation executed: Restarted api-gateway container instances." },
      { id: "log-5", timestamp: "07:40:15", level: "AGENT", source: "Verification Agent", message: "VERIFICATION FAILED: Error rate 12.4% persists. Restart did not resolve root cause." },
      { id: "log-6", timestamp: "07:41:00", level: "AGENT", source: "Diagnostic Agent", message: "RE-DIAGNOSIS: Root cause isolated to commit 9bf2ad4 (keepalive: 250ms). Proposing Helm rollback." },
      { id: "log-7", timestamp: "07:42:00", level: "AGENT", source: "Remediation Agent", message: "Safety check flagged CRITICAL risk. Approval APP-401 created for Human-In-The-Loop confirmation." },
    ],
  },
  {
    id: "INC-8919",
    fingerprint: "c3d4a1b0-ddos-auth-flood",
    title: "Auth Service Credential Stuffing & Rate Limit Saturation",
    severity: "SEV-1",
    status: "approval_required",
    leadAgentId: "agent-diagnostic",
    affectedServices: ["auth-service"],
    blastRadius: "120 rogue IP sources targeting /auth/login",
    summary: "High-volume credential brute-force attack detected on auth-service login endpoints, spiking CPU to 88%.",
    createdAt: "2026-09-28T07:22:40Z",
    updatedAt: "2026-09-28T07:41:10Z",
    duration: "18m 30s",
    rca: {
      rootCause: "Distributed botnet targeting login endpoint without client IP throttling.",
      confidence: 94.0,
      evidence: [
        {
          type: "metric",
          content: "Auth failure rate increased from 1.2% to 58.4%",
          timestamp: "2026-09-28T07:23:00Z",
        },
      ],
      suggestedMitigation: "Inject dynamic rate-limiting rule (20 req/min per IP) on auth-service config.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Diagnostic Agent: Isolated rogue botnet IP cluster",
        status: "completed",
        executedBy: "Diagnostic Agent",
        executedAt: "07:25:00 UTC",
      },
      {
        id: "step-2",
        title: "Remediation: Apply rate limiting config (modify_config)",
        command: "sentinel-ctl config patch auth-service --set rate_limit=20/m",
        status: "requires_approval",
        executedBy: "Remediation Agent",
        executedAt: "07:31:00 UTC",
      },
    ],
    telemetry: [
      { timestamp: "07:20", errorRate: 0.8, latencyMs: 22, requestCount: 320 },
      { timestamp: "07:24", errorRate: 18.4, latencyMs: 64, requestCount: 920 },
      { timestamp: "07:28", errorRate: 12.0, latencyMs: 54, requestCount: 880 },
    ],
    logs: [
      { id: "sec-1", timestamp: "07:22:40", level: "WARN", source: "auth-service", message: "Spike in HTTP 401 Unauthorized on /login" },
      { id: "sec-2", timestamp: "07:31:00", level: "AGENT", source: "Remediation Agent", message: "Approval APP-402 created for dynamic rate-limiting rule injection." },
    ],
  },
  {
    id: "INC-8914",
    fingerprint: "f0e9d8c7-postgres-connections",
    title: "PostgreSQL Connection Pool Saturation on Primary",
    severity: "SEV-2",
    status: "resolved",
    leadAgentId: "agent-diagnostic",
    affectedServices: ["postgres-primary"],
    blastRadius: "Database queries queued; latency increased by 35ms",
    summary: "Long-running analytical query held table lock, exhausting active connection slots.",
    createdAt: "2026-09-28T06:55:10Z",
    updatedAt: "2026-09-28T07:15:00Z",
    duration: "19m 50s",
    rca: {
      rootCause: "Unindexed analytical query blocked backend worker threads.",
      confidence: 96.0,
      evidence: [
        {
          type: "metric",
          content: "pg_stat_activity active connections reached 290/300 limit",
          timestamp: "2026-09-28T07:05:00Z",
        },
      ],
      suggestedMitigation: "Terminate blocking query PID and adjust max_connections to 600.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Terminate blocking query PID 41802",
        status: "completed",
        executedBy: "Remediation Agent",
        executedAt: "07:12:00 UTC",
      },
      {
        id: "step-2",
        title: "Verification passed: Active connections dropped to 42",
        status: "completed",
        executedBy: "Verification Agent",
        executedAt: "07:14:30 UTC",
      },
    ],
    telemetry: [
      { timestamp: "06:50", errorRate: 0.0, latencyMs: 8, requestCount: 1200 },
      { timestamp: "07:05", errorRate: 0.8, latencyMs: 45, requestCount: 1250 },
      { timestamp: "07:15", errorRate: 0.0, latencyMs: 8, requestCount: 1200 },
    ],
    logs: [
      { id: "db-1", timestamp: "06:55:10", level: "WARN", source: "postgres-primary", message: "Active connections > 90% threshold" },
      { id: "db-2", timestamp: "07:12:00", level: "AGENT", source: "Remediation Agent", message: "Terminated query PID 41802." },
      { id: "db-3", timestamp: "07:15:00", level: "AGENT", source: "Verification Agent", message: "Incident resolved. Connection count healthy." },
    ],
  },
  {
    id: "INC-8902",
    fingerprint: "b2c3d4e5-billing-oom",
    title: "Billing Service PDF Worker Container OOMKilled",
    severity: "SEV-3",
    status: "resolved",
    leadAgentId: "agent-diagnostic",
    affectedServices: ["billing-service"],
    blastRadius: "Isolated to background receipt rendering worker",
    summary: "Unclosed file handles caused gradual memory growth until container cgroup limit was reached.",
    createdAt: "2026-09-28T04:10:00Z",
    updatedAt: "2026-09-28T04:22:15Z",
    duration: "12m 15s",
    rca: {
      rootCause: "Ghostscript subprocess handles not freed after invoice rendering.",
      confidence: 99.0,
      evidence: [
        {
          type: "metric",
          content: "container_memory_working_set_bytes hit 512MB limit",
          timestamp: "2026-09-28T04:15:00Z",
        },
      ],
      suggestedMitigation: "Increase memory limit to 1GB and restart worker container.",
    },
    mitigationSteps: [
      {
        id: "step-1",
        title: "Remediation: Modify memory limits and restart container",
        command: "modify_config billing-service --memory 1024M && restart_container billing-service",
        status: "completed",
        executedBy: "Remediation Agent",
        executedAt: "04:18:00 UTC",
      },
      {
        id: "step-2",
        title: "Verification passed: 0 restarts over 15m window",
        status: "completed",
        executedBy: "Verification Agent",
        executedAt: "04:22:00 UTC",
      },
    ],
    telemetry: [
      { timestamp: "04:00", errorRate: 0.0, latencyMs: 28, requestCount: 410 },
      { timestamp: "04:15", errorRate: 1.8, latencyMs: 35, requestCount: 420 },
      { timestamp: "04:22", errorRate: 0.0, latencyMs: 28, requestCount: 410 },
    ],
    logs: [
      { id: "oom-1", timestamp: "04:15:02", level: "FATAL", source: "billing-service", message: "Container killed (OOMKilled, exit code 137)" },
      { id: "oom-2", timestamp: "04:18:00", level: "AGENT", source: "Remediation Agent", message: "Patched memory limit to 1GB and restarted container." },
      { id: "oom-3", timestamp: "04:22:15", level: "AGENT", source: "Verification Agent", message: "Incident resolved. Memory usage stable at 340MB." },
    ],
  },
];

export const mockApprovals: ApprovalRequest[] = [
  {
    id: "APP-401",
    incidentId: "INC-8921",
    incidentTitle: "API Gateway 502 Cascading Spike & Upstream Connection Reset",
    incidentSeverity: "SEV-0",
    agentId: "agent-remediation",
    agentName: "Remediation Agent",
    title: "Canary Helm Rollback: api-gateway v3.8.2 → v3.8.1",
    action: "Helm Canary Rollback",
    target: "api-gateway (Production Cluster)",
    reason: "Ingress keepalive timeout configured to 250ms causing cascading 502 socket resets and 14.8% error rate across 1,850 req/s.",
    expectedResult: "Restores gRPC keepalive baseline to 30s; drops HTTP 502 error rate below 0.05% in under 60s with zero downtime.",
    description: "Remediation Agent requests authorization for automated canary rollback of api-gateway to previous stable release after first restart mitigation failed.",
    riskLevel: "CRITICAL",
    status: "pending",
    createdAt: "2026-09-28T07:42:00Z",
    expiresInSeconds: 300,
    blastRadius: [
      "api-gateway production container instances",
      "Live Ingress Traffic (1,850 req/sec)",
      "Zero-downtime rolling replacement guarantee",
    ],
    toolName: "modify_config",
    actionDiff: {
      type: "cli",
      before: "# Current Deployment: api-gateway v3.8.2\ngrpc:\n  keepalive:\n    time: 250ms # <-- BUG: Causes upstream socket termination\n    timeout: 100ms",
      after: "# Proposed Rollback: api-gateway v3.8.1\ngrpc:\n  keepalive:\n    time: 30000ms # Restored to 30s stable baseline\n    timeout: 5000ms\n\n$ helm rollback api-gateway 14 --namespace production --wait",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Target Revision Integrity Check",
        status: "passed",
        details: "Revision 14 hash sha256:4a81bc verified against GitOps repository.",
      },
      {
        id: "sc-2",
        name: "Database Schema Compatibility",
        status: "passed",
        details: "No database migrations occurred between v3.8.1 and v3.8.2.",
      },
      {
        id: "sc-3",
        name: "Active Connection Draining",
        status: "warning",
        details: "Active in-flight connections will be gracefully drained within 5 seconds.",
      },
    ],
  },
  {
    id: "APP-402",
    incidentId: "INC-8919",
    incidentTitle: "Auth Service Credential Stuffing & Rate Limit Saturation",
    incidentSeverity: "SEV-1",
    agentId: "agent-remediation",
    agentName: "Remediation Agent",
    title: "Inject Rate-Limiting Rule on /auth/login (20 req/min per IP)",
    action: "Dynamic Rate-Limiting Config Injection",
    target: "auth-service (ConfigMap: auth-ratelimit-policy)",
    reason: "High-volume credential brute-force attack generating 920 requests/sec with 58% auth failures.",
    expectedResult: "Blocks abusive client IPs while allowing 100% of legitimate customer logins.",
    description: "Remediation Agent requests approval to inject dynamic rate-limiting rule to suppress brute-force flood.",
    riskLevel: "HIGH",
    status: "pending",
    createdAt: "2026-09-28T07:31:00Z",
    expiresInSeconds: 480,
    blastRadius: [
      "auth-service /auth/login endpoint",
      "Rate limit policy applied to untrusted client IPs",
    ],
    toolName: "modify_config",
    actionDiff: {
      type: "cli",
      before: "# auth-service config\nrate_limit:\n  enabled: false",
      after: "# auth-service config\nrate_limit:\n  enabled: true\n  max_requests: 20\n  window_seconds: 60\n  action: block_ip",
    },
    safetyChecks: [
      {
        id: "sc-1",
        name: "Corporate Allowlist Check",
        status: "passed",
        details: "Corporate VPN and internal microservices excluded from rate limit.",
      },
    ],
  },
  {
    id: "APP-403",
    incidentId: "INC-8914",
    incidentTitle: "PostgreSQL Connection Pool Saturation",
    incidentSeverity: "SEV-2",
    agentId: "agent-remediation",
    agentName: "Remediation Agent",
    title: "Terminate Blocking PostgreSQL Query PID 41802",
    action: "Terminate Blocking Database Backend",
    target: "postgres-primary (PID: 41802)",
    reason: "Unindexed analytical query holding exclusive table lock on audit_events.",
    expectedResult: "Frees 248 queued connection handles immediately.",
    description: "Remediation Agent terminated blocking query after timeout threshold was exceeded.",
    riskLevel: "MEDIUM",
    status: "approved",
    createdAt: "2026-09-28T07:11:00Z",
    expiresInSeconds: 0,
    blastRadius: ["Isolated analytical query thread; zero impact on primary transaction pool"],
    toolName: "restart_container",
    safetyChecks: [
      {
        id: "sc-1",
        name: "Read-Only Query Verification",
        status: "passed",
        details: "Verified target PID is executing a SELECT statement; 0 data mutation risk.",
      },
    ],
    decidedAt: "2026-09-28T07:11:30Z",
    decidedBy: "SRE Lead",
  },
];

export const mockTools: ToolDefinition[] = [
  {
    id: "check_health",
    name: "check_health",
    category: "cloud",
    safetyTier: "read_only",
    description: "Execute HTTP and gRPC health checks against service endpoints, verifying latency SLAs and error rates.",
    requiredApprovalRole: "None",
    enabled: true,
    rateLimit: "120 req/min",
    allowedAgents: ["agent-diagnostic", "agent-verification"],
    totalExecutions: 840,
    lastExecutedAt: "2026-09-28T07:44:10Z",
    recentExecutions: [
      {
        id: "ex-1",
        agentId: "agent-verification",
        incidentId: "INC-8921",
        command: "check_health --service api-gateway --endpoint /healthz",
        durationMs: 42,
        exitCode: 0,
        timestamp: "07:44:10",
      },
    ],
  },
  {
    id: "get_logs",
    name: "get_logs",
    category: "cloud",
    safetyTier: "read_only",
    description: "Fetch and filter real-time container logs, error stack traces, and distributed telemetry events.",
    requiredApprovalRole: "None",
    enabled: true,
    rateLimit: "180 req/min",
    allowedAgents: ["agent-diagnostic", "agent-verification"],
    totalExecutions: 1240,
    lastExecutedAt: "2026-09-28T07:41:00Z",
    recentExecutions: [
      {
        id: "ex-2",
        agentId: "agent-diagnostic",
        incidentId: "INC-8921",
        command: "get_logs --container api-gateway --tail 100 --level ERROR",
        durationMs: 95,
        exitCode: 0,
        timestamp: "07:41:00",
      },
    ],
  },
  {
    id: "container_status",
    name: "container_status",
    category: "kubernetes",
    safetyTier: "read_only",
    description: "Inspect container lifecycle status, CPU/memory cgroup usage, restart counts, and network sockets.",
    requiredApprovalRole: "None",
    enabled: true,
    rateLimit: "120 req/min",
    allowedAgents: ["agent-diagnostic", "agent-remediation"],
    totalExecutions: 620,
    lastExecutedAt: "2026-09-28T07:38:40Z",
    recentExecutions: [
      {
        id: "ex-3",
        agentId: "agent-diagnostic",
        incidentId: "INC-8921",
        command: "container_status --all",
        durationMs: 65,
        exitCode: 0,
        timestamp: "07:38:40",
      },
    ],
  },
  {
    id: "restart_container",
    name: "restart_container",
    category: "kubernetes",
    safetyTier: "reversible",
    description: "Gracefully restart single or multiple container replicas with automatic health checks.",
    requiredApprovalRole: "SRE_Lead",
    enabled: true,
    rateLimit: "30 req/min",
    allowedAgents: ["agent-remediation"],
    totalExecutions: 84,
    lastExecutedAt: "2026-09-28T07:39:30Z",
    recentExecutions: [
      {
        id: "ex-4",
        agentId: "agent-remediation",
        incidentId: "INC-8921",
        command: "restart_container api-gateway",
        durationMs: 820,
        exitCode: 0,
        timestamp: "07:39:30",
      },
    ],
  },
  {
    id: "modify_config",
    name: "modify_config",
    category: "kubernetes",
    safetyTier: "high_risk",
    description: "Patch service environment variables, resource limits, ConfigMaps, or trigger version rollbacks.",
    requiredApprovalRole: "Incident_Commander",
    enabled: true,
    rateLimit: "15 req/min",
    allowedAgents: ["agent-remediation"],
    totalExecutions: 38,
    lastExecutedAt: "2026-09-28T07:42:00Z",
    recentExecutions: [
      {
        id: "ex-5",
        agentId: "agent-remediation",
        incidentId: "INC-8921",
        command: "helm rollback api-gateway 14",
        durationMs: 1400,
        exitCode: 0,
        timestamp: "07:42:00",
      },
    ],
  },
  {
    id: "delete_container",
    name: "delete_container",
    category: "kubernetes",
    safetyTier: "destructive",
    description: "Force kill or remove an unhealthy container instance to trigger clean scheduler replacement.",
    requiredApprovalRole: "Incident_Commander",
    enabled: false,
    rateLimit: "5 req/min",
    allowedAgents: ["agent-remediation"],
    totalExecutions: 6,
    lastExecutedAt: "2026-09-27T18:20:00Z",
    recentExecutions: [],
  },
];

export const mockRecoveryStats: RecoveryStats = {
  mttd: "42s",
  mttm: "4m 12s",
  autonomousResolutionRate: 92.4,
  totalIncidentsResolved: 48,
  preventedDowntimeMinutes: 38,
  estimatedCostSaved: "99.98% SLA",
  activeCanaryVerifications: 1,
  rollbackReliability: 99.4,
};

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: "act-1",
    timestamp: "07:42:00",
    category: "approval",
    agentName: "Remediation Agent",
    agentRole: "Autonomous Mitigation",
    summary: "Approval APP-401 submitted: Helm Canary Rollback to v3.8.1",
    details: "Safety check flagged CRITICAL risk. Awaiting Human-In-The-Loop approval.",
    status: "pending",
    targetResource: "api-gateway",
  },
  {
    id: "act-2",
    timestamp: "07:41:00",
    category: "recovery",
    agentName: "Diagnostic Agent",
    agentRole: "Root Cause Analysis",
    summary: "Re-Diagnosis: Isolated commit 9bf2ad4 keepalive regression (250ms)",
    details: "Suggested action: Roll back api-gateway to v3.8.1",
    status: "success",
    targetResource: "api-gateway",
  },
  {
    id: "act-3",
    timestamp: "07:40:15",
    category: "telemetry",
    agentName: "Verification Agent",
    agentRole: "SLO Validation",
    summary: "Verification Failed: 12.4% error rate persists after container restart",
    details: "First remediation failed to fix underlying root cause. Re-triage triggered.",
    status: "failed",
    targetResource: "api-gateway",
  },
  {
    id: "act-4",
    timestamp: "07:39:30",
    category: "mitigation",
    agentName: "Remediation Agent",
    agentRole: "Autonomous Mitigation",
    summary: "Executed restart_container on api-gateway instances",
    details: "First mitigation attempt executed in 820ms.",
    status: "success",
    targetResource: "api-gateway",
  },
  {
    id: "act-5",
    timestamp: "07:38:40",
    category: "recovery",
    agentName: "Diagnostic Agent",
    agentRole: "Root Cause Analysis",
    summary: "SEV-0 Incident INC-8921 opened on api-gateway (502 Outage)",
    details: "Calculated blast radius: 1,850 req/sec affected.",
    status: "warning",
    targetResource: "api-gateway",
  },
];
